name: enough_mail
description: IMAP, POP3 and SMTP for email developers. Choose between a low
  level and a high level API for mailing. Parse and generate MIME messages.
  Discover email settings.
version: 2.1.7
homepage: https://github.com/Enough-Software/enough_mail
topics:
  - email
  - imap
  - pop3
  - smtp
  - mime


environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  basic_utils: any
  collection: any
  crypto: any
  # encrypt: any
  encrypter_plus: any
  enough_convert: any
  event_bus: any
  intl: any
  json_annotation: any
  pointycastle: any
  synchronized: any
  xml: any

dependency_overrides:
  # http: ^1.4.0 # for dart_code_metrics

dev_dependencies:
  build_runner: any
  # dart_code_metrics: any
  dart_code_linter: any
  flutter_lints: any
  json_serializable: any
  lints: any
  test: any
  timezone: any
